import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync,spawnSync} from 'node:child_process';
import {resolveLocalApprovalInstallConfig} from '../scripts/local-approval-install-config.mjs';
import {plist} from '../scripts/dispatcher-host-artifact.mjs';
const mac={skip:process.platform!=='darwin'};
function fixture(t){const d=fs.mkdtempSync(path.join(fs.realpathSync(os.homedir()),'.dona-approval-install-'));fs.chmodSync(d,0o700);t.after(()=>fs.rmSync(d,{recursive:true,force:true}));const config=path.join(d,'approval<&.json');fs.writeFileSync(config,'{"codec_version":1}',{mode:0o600});const installed=path.join(d,'dispatcher.plist'),root=path.join(d,'config');const save=(target=config,configRoot=root)=>fs.writeFileSync(installed,plist({Label:'dev.dona.dispatcher',EnvironmentVariables:{DONA_LOCAL_APPROVAL_CONFIG:target,DOTENV_CONFIG_PATH:path.join(configRoot,'dispatcher.env')}}),{mode:0o600});return {d,config,installed,root,save};}
test('明示設定と同generation既存設定を保持し、明示変更だけを優先する',mac,t=>{const f=fixture(t);assert.equal(resolveLocalApprovalInstallConfig('',f.installed,f.root),undefined);f.save();assert.equal(resolveLocalApprovalInstallConfig('',f.installed,f.root),f.config);const next=path.join(f.d,'next.json');fs.writeFileSync(next,'{}',{mode:0o600});assert.equal(resolveLocalApprovalInstallConfig(next,f.installed,f.root),next);f.save(f.config,path.join(f.d,'other'));assert.throws(()=>resolveLocalApprovalInstallConfig('',f.installed,f.root));});
test('relative/missing/public/symlink/hardlink/writable parentと不正既存plistを拒否する',mac,t=>{const f=fixture(t);for(const p of ['relative.json',path.join(f.d,'missing')])assert.throws(()=>resolveLocalApprovalInstallConfig(p,undefined,f.root));fs.chmodSync(f.config,0o644);assert.throws(()=>resolveLocalApprovalInstallConfig(f.config,undefined,f.root));fs.chmodSync(f.config,0o600);const alias=path.join(f.d,'alias');fs.symlinkSync(f.config,alias);assert.throws(()=>resolveLocalApprovalInstallConfig(alias,undefined,f.root));fs.unlinkSync(alias);fs.linkSync(f.config,alias);assert.throws(()=>resolveLocalApprovalInstallConfig(f.config,undefined,f.root));fs.unlinkSync(alias);fs.chmodSync(f.d,0o777);assert.throws(()=>resolveLocalApprovalInstallConfig(f.config,undefined,f.root));fs.chmodSync(f.d,0o700);f.save();fs.chmodSync(f.installed,0o644);assert.throws(()=>resolveLocalApprovalInstallConfig('',f.installed,f.root));});
test('実rendererはescaped pathをplistへ保存し省略更新でも保持、失敗時に成果物を作らない',mac,t=>{const f=fixture(t);const bin=path.join(f.d,'bin');fs.mkdirSync(bin);for(const name of ['npm','gh','git','herdr','codex'])fs.writeFileSync(path.join(bin,name),'#!/bin/sh\nexit 0\n',{mode:0o700});const run=(out,input)=>spawnSync(process.execPath,['scripts/render-self-update-templates.mjs',out,'a'.repeat(40),f.d,'','','',input,f.installed],{encoding:'utf8',env:{...process.env,PATH:bin+':/usr/bin:/bin'}});const a=path.join(f.d,'first');let r=run(a,f.config);assert.equal(r.status,0,r.stderr);const file=path.join(a,'dev.dona.dispatcher.plist');const value=JSON.parse(execFileSync('/usr/bin/plutil',['-convert','json','-o','-',file],{encoding:'utf8'}));assert.equal(value.EnvironmentVariables.DONA_LOCAL_APPROVAL_CONFIG,f.config);assert.equal(value.ProgramArguments[2],'serve');fs.copyFileSync(file,f.installed);fs.chmodSync(f.installed,0o600);r=run(path.join(f.d,'second'),'');assert.equal(r.status,0,r.stderr);const next=JSON.parse(execFileSync('/usr/bin/plutil',['-convert','json','-o','-',path.join(f.d,'second/dev.dona.dispatcher.plist')],{encoding:'utf8'}));assert.deepEqual(next,value);fs.chmodSync(f.config,0o644);const rejected=path.join(f.d,'rejected');r=run(rejected,'');assert.notEqual(r.status,0);assert.equal(fs.existsSync(rejected),false);assert.doesNotMatch(r.stderr,/codec_version/);});
