import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import Database from 'better-sqlite3';
import {openLocalApprovalDatabase,createLocalApprovalNodeDatabase} from '../src/approval/local-database.js';
import {SqliteUsedTransactionNodes} from '../src/approval/used-transaction-store.js';
import {emptyUsedTransactionRoot,prepareUsedTransactionInsert} from '../src/approval/used-transactions.js';
function fixture(t:test.TestContext){const root=fs.mkdtempSync(path.join(fs.realpathSync(os.homedir()),'.dona-native-db-'));fs.chmodSync(root,0o700);t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return root;}
function ready(db:Database.Database){assert.equal(db.pragma('journal_mode',{simple:true}),'wal');assert.equal(db.pragma('synchronous',{simple:true}),2);assert.equal(db.pragma('foreign_keys',{simple:true}),1);}
test('本体接続は既存Task DBを保持しWAL/FULL/FKをconnectionごとに設定する',t=>{const root=fixture(t),file=path.join(root,'dispatcher.sqlite');const old=new Database(file);fs.chmodSync(file,0o600);old.exec("CREATE TABLE tasks(id TEXT PRIMARY KEY); INSERT INTO tasks VALUES('preserved'); PRAGMA user_version=4;");old.pragma('journal_mode=WAL');old.close();for(let i=0;i<2;i++){const db=openLocalApprovalDatabase(file);try{ready(db);assert.equal(db.pragma('user_version',{simple:true}),4);assert.deepEqual(db.prepare('SELECT id FROM tasks').all(),[{id:'preserved'}]);}finally{db.close();}}});
test('初回provisionと同じ実openerが新品node DBへschema・immutable nodeを耐久保存する',t=>{const root=fixture(t),file=path.join(root,'nodes.sqlite');const db=createLocalApprovalNodeDatabase(file);const scope={instance_id:'instance',ledger_id:'ledger',purpose:'audit_anchor' as const};let expected:string;try{ready(db);const nodes=new SqliteUsedTransactionNodes(db),insert=prepareUsedTransactionInsert(scope,emptyUsedTransactionRoot(scope),'genesis',d=>nodes.read(d));nodes.stage(insert.nodes);expected=insert.nodes[0]!.digest;assert.ok(nodes.read(expected));assert.throws(()=>createLocalApprovalNodeDatabase(file),/EEXIST/);}finally{db.close();}const reopened=openLocalApprovalDatabase(file);try{ready(reopened);assert.ok(new SqliteUsedTransactionNodes(reopened).read(expected!));}finally{reopened.close();}});
test('作成後中断した空file・既存DB・symlinkは削除/再初期化せず状態を保持する',t=>{const root=fixture(t),file=path.join(root,'partial.sqlite');fs.writeFileSync(file,'',{mode:0o600});const before=fs.statSync(file);assert.throws(()=>createLocalApprovalNodeDatabase(file),/EEXIST/);assert.equal(fs.statSync(file).ino,before.ino);assert.equal(fs.statSync(file).size,0);const alias=path.join(root,'alias.sqlite');fs.symlinkSync(file,alias);assert.throws(()=>createLocalApprovalNodeDatabase(alias));assert.equal(fs.statSync(file).size,0);const unsafe=path.join(root,'unsafe');fs.mkdirSync(unsafe,{mode:0o777});fs.chmodSync(unsafe,0o777);assert.throws(()=>createLocalApprovalNodeDatabase(path.join(unsafe,'never-created')),/path_invalid/);assert.equal(fs.existsSync(path.join(unsafe,'never-created')),false);});
test('通常openは既存非WAL DBを修復せず拒否する',t=>{const root=fixture(t),file=path.join(root,'legacy.sqlite');const original=new Database(file);fs.chmodSync(file,0o600);original.exec('CREATE TABLE sentinel(value); INSERT INTO sentinel VALUES(1)');original.close();assert.throws(()=>openLocalApprovalDatabase(file),/database_unverified/);const check=new Database(file,{readonly:true});try{assert.equal(check.pragma('journal_mode',{simple:true}),'delete');assert.equal(check.prepare('SELECT value FROM sentinel').pluck().get(),1);}finally{check.close();}});
